// chess-react/src/App.js
import React from 'react';
import './App.css';
import Grid from '@material-ui/core/Grid';
function App() {
  return (
    <div className="App">
      <Board></Board>
    </div>
  );
}

function Piece(props){
    switch(props.value.piece) {
        case 'rook':
            return <button><img src = {require('./assets/pieces/rook.png')} style={props.value.inputStyle}></img></button>;
        break;
        case 'horse':
            return <button><img src = {require('./assets/pieces/horse.png')} style={props.value.inputStyle}></img></button>;
        break;
        case 'bishop':
            return <button><img src = {require('./assets/pieces/bishop.png')} style={props.value.inputStyle}></img></button>;
        break;
        case 'pawn':
            return <button><img src = {require('./assets/pieces/pawn.png')} style={props.value.inputStyle}></img></button>;
        break;
        case 'king':
            return <button><img src = {require('./assets/pieces/king.png')} style={props.value.inputStyle}></img></button>;
        break;
        case 'queen':
            return <button><img src = {require('./assets/pieces/queen.png')} style={props.value.inputStyle}></img></button>;
        break;

        case 'wrook':
            return <button><img src = {require('./assets/pieces/wrook.png')} style={props.value.inputStyle}></img></button>;
            break;
        case 'whorse':
            return <button><img src = {require('./assets/pieces/whorse.png')} style={props.value.inputStyle}></img></button>;
            break;
        case 'wbishop':
            return <button><img src = {require('./assets/pieces/wbishop.png')} style={props.value.inputStyle}></img></button>;
            break;
        case 'wpawn':
            return <button><img src = {require('./assets/pieces/wpawn.png')} style={props.value.inputStyle}></img></button>;
            break;
        case 'wking':
            return <button><img src = {require('./assets/pieces/wking.png')} style={props.value.inputStyle}></img></button>;
            break;
        case 'wqueen':
            return <button><img src = {require('./assets/pieces/wqueen.png')} style={props.value.inputStyle}></img></button>;
            break;
        default:
            return <button><img className="empty" style={props.value.inputStyle}></img></button>;
    }
}
class Board extends React.Component {

    table: string[];
    constructor(){
        super();
        this.table = [];
        for(let  i = 0; i < 8; ++i){
            this.table.push([])
            for(let  j = 0; j < 8; ++j){
                if(i === 0 && j === 0){
                    this.table[i].push({piece: 'rook', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 0 && j === 1){
                    this.table[i].push({piece:'horse', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 0 && j === 2){
                    this.table[i].push({piece:'bishop', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 0 && j === 3){
                    this.table[i].push({piece:'king', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 0 && j === 4){
                    this.table[i].push({piece:'queen', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 0 && j === 5){
                    this.table[i].push({piece:'bishop', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 0 && j === 6){
                    this.table[i].push({piece:'horse', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 0 && j === 7){
                    this.table[i].push({piece:'rook', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 1){
                    this.table[i].push({piece:'pawn', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else

                if(i === 7 && j === 0){
                    this.table[i].push({piece:'wrook', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 7 && j === 7){
                    this.table[i].push({piece:'wrook', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 7 && j === 6){
                    this.table[i].push({piece:'whorse', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 7 && j === 5){
                    this.table[i].push({piece:'wbishop', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 7&& j === 4){
                    this.table[i].push({piece:'wqueen', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 7 && j === 3){
                    this.table[i].push({piece:'wking', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 7 && j === 2){
                    this.table[i].push({piece:'wbishop', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                if(i === 7 && j === 1){
                    this.table[i].push({piece:'whorse', inputStyle: {
                        width: "75px",
                            height: "75px",
                    }});
                }else
                if(i === 6){
                    this.table[i].push({piece:'wpawn', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }else
                {
                    this.table[i].push({piece:'', inputStyle: {
                            width: "75px",
                            height: "75px",
                        }});
                }
            }
        }
    }

    render(){
        return (
            <div className="App">
                {this.table.map((table,i) =>
                    <Grid
                        container
                        direction="row"
                        justify="center"
                        alignItems="center"
                    >
                        <Grid
                            container
                            direction="row"
                            justify="center"
                            alignItems="center"
                        >
                            {table.map((elems,j) =>
                            <Piece value={elems}></Piece>

                            )}
                        </Grid>
                    </Grid>
                )}

            </div>
        );
    }



    handleClick(x,y){
        window.alert(x + ',' + y);
    }
}

export default App;

// chessApplication/src/app/app.component.ts
import { Component ,OnInit} from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit{
  constructor(private translate: TranslateService) {
    translate.setDefaultLang('tr');
  }

  switchLanguage(language: string) {
    this.translate.use(language);
  }

  public ngOnInit()
  {

  }
  varDeneme;
    tableContent=[[{id:0,piece:"wrook"},{id:1,piece:"whorse"},{id:2,piece:"wbishop"},{id:3,piece:"wqueen"},
      {id:4,piece:"wking"},{id:5,piece:"wbishop"},{id:6,piece:"whorse"},{id:7,piece:"wrook"}],

  [{id:0,piece:"wpawn"},{id:1,piece:"wpawn"},{id:2,piece:"wpawn"},{id:3,piece:"wpawn"},
{id:4,piece:"wpawn"},{id:5,piece:"wpawn"},{id:6,piece:"wpawn"},{id:7,piece:"wpawn"}],

[{id:0,piece:"space"},{id:1,piece:"space"},{id:2,piece:"space"},{id:3,piece:"space"},
  {id:4,piece:"space"},{id:5,piece:"space"},{id:6,piece:"space"},{id:7,piece:"space"}],

  [{id:0,piece:"space"},{id:1,piece:"space"},{id:2,piece:"space"},{id:3,piece:"space"},
    {id:4,piece:"space"},{id:5,piece:"space"},{id:6,piece:"space"},{id:7,piece:"space"}],

  [{id:0,piece:"space"},{id:1,piece:"space"},{id:2,piece:"space"},{id:3,piece:"space"},
    {id:4,piece:"space"},{id:5,piece:"space"},{id:6,piece:"space"},{id:7,piece:"space"}],

  [{id:0,piece:"space"},{id:1,piece:"space"},{id:2,piece:"space"},{id:3,piece:"space"},
    {id:4,piece:"space"},{id:5,piece:"space"},{id:6,piece:"space"},{id:7,piece:"space"}],

  [{id:0,piece:"pawn"},{id:1,piece:"pawn"},{id:2,piece:"pawn"},{id:3,piece:"pawn"},
    {id:4,piece:"pawn"},{id:5,piece:"pawn"},{id:6,piece:"pawn"},{id:7,piece:"pawn"}],

  [{id:0,piece:"rook"},{id:1,piece:"horse"},{id:2,piece:"bishop"},{id:3,piece:"queen"},
    {id:4,piece:"king"},{id:5,piece:"bishop"},{id:6,piece:"horse"},{id:7,piece:"rook"}]
];

  onTableTriggered(value){
    this.varDeneme=value.piece;
  }



}

<app-header-component></app-header-component>
<app-table-component (TableEvent)="onTableTriggered($event)" [ChessTable]="tableContent"></app-table-component>
<app-piece-component [deneme]="varDeneme"></app-piece-component>
